### ISSUE TITLE
原版に存在する問題点の修正

### ISSUE THREAD

**Issue by wtsnjp** [wtsnjp/platexcheat#1]
本文書の原版（[LaTeX2e Cheat Sheet](http://wch.github.io/latexsheet/)）には多数 “不適切な点” が存在します．既に “明らかに LaTeX2e の命令でない制御綴” を除外するなどの変更は行っていますが，さしあたって現状は “翻訳に毛が生えたモノ” 状態です．今後，使用頻度の低い命令を省略して頻度が高いのに漏れている命令を追加するなど，pLaTeX2e 版独自の工夫が必要です．

具体的な修正の方針を以下に箇条書きしておきます：

- [x] “プリアンブルに書くモノ” を明確に分離してまとめる
- [x] 空白関連命令の充実化（寸法単位や LaTeX のボックスにも言及？）
- [x] “その他” の項に掲載している命令の選択が奇妙な点を修正
- [x] 可能なら TeX や LaTeX のロゴ出力命令への言及を追加
- [x] tabbing 環境，tabular 環境の説明を整理・増強
- [x] 数式モード周りは分類・順番の整理と大幅な命令の追加が必要
- [x] 索引について言及
- [x] thebibliography 環境についての記述を追加
- [x] BibTeX 周りの説明は削減または削除
- [x] 文書サンプルも大幅改訂または削減または削除

またソースコード自体も（原版から引き継いだまま）スパゲティ状態なので，もっときちんと構造化したいと考えています．

**Comment by zr-tex8r** [comment]
原版にある問題点でこちらでまだ残っているもの。

（ただしBibTeXと数式モードは保留）

  * commentという環境はLaTeXには存在しない。
  * それより `%` の説明を入れるべきでは。
  * `\kill` はtabbing環境専用の命令（外で使った場合の動作は未定義）だからtabbingの説明で扱うので十分かも。
  * アクセント命令について
      * `\c` が2つある。たぶん「`\c o`」の方は「`\u o`」の誤記だと思う。
      * なぜか `\ss` がない。
      * ``!` `` が ``~` `` になっている。

**Comment by wtsnjp** [comment]
コメントありがとうございます．

ご指摘のもののように，原版の “改善点” というよりは “明らかに不具合な点” については優先的に修正して，バージョン 1.x としてリリースすることにします．

私が最初に列挙したような “改善点” は徐々に修正して，完了次第バージョン 2.0 としてリリースすることにしようと思います．

なお，どのタイミングで CTAN に上げるかは思案中です．（進捗次第）

**Comment by wtsnjp** [comment]
最初に示したすべての修正項目を達成した v2.0-beta をリリースしました．
思った以上に手を加える必要があり，もはや原版からはコンセプトぐらいしか引き継いでいません．
組版済み PDF を一時的に置いておきます：<https://wtsnjp.com/pdf/platexsheet-v2.0-beta.pdf>

校正と修正を行い，1/7を目処に v2.0 として正式リリースするつもりでいます．
v2.0 リリース後は速やかに CTAN へのアップロードも行う予定です．

**Comment by zr-tex8r** [comment]
「LaTeXジャナイ」情報です。（ #LaTeX警察 ）

  * LaTeXではfillレベルの無限長のみを用いる。
      * だから `\hfil`、`\vfil` はない。
      * この事実はTeXのプログラミングでも利用される。
  * LaTeXの用語には「制御綴（control sequence）」はない。あるのは「命令（command）」だけ。
      * ただ自分も時々LaTeX者向け文書で「制御綴」を使っている気がする。
      * 個人的には、「命令」で済む箇所は「命令」がよいと思う。
  * `\break` は非LaTeX。
      * これに相当するのは、行では `\linebreak`、ページでは `\pagebreak`。
      * ちなみに、`\pagebreak` と `\newpage` も `\flushbottom` の時には挙動は違う。
  * `\llap`・`\rlap` は非LaTeX。
      * これに相当するのは `\makebox[0pt]...`。
      * これらは段落頭では `\leavevmode` が必要。
      * 特に `Y\llap{=}` はマネされる恐れがあり非常にまずい。
  * 厳密にいうと `\mathbin` などの数式クラス指定のプリミティブも非LaTeXらしい。
      * ただこれは自分もLaTeXに“昇格”させている。

**Comment by zr-tex8r** [comment]
その他の「私気になります」情報。

  * 「65536sp = 1in」じゃなくて「65536sp = 1pt」。
  * 行列は `\begin{tabular}` じゃなくて `\begin{array}`。
  * `\deisplaystyle` じゃなくて `\displaystyle`。
  * `\tableoffigures` じゃなくて `\listoffigures`。
  * `\tableoftables` じゃなくて `\listoftables`。
  * `\printindex` は標準では定義されていない（困ったね）。
      * makeidx パッケージの読込が必要。
  * jbibtexよりもpbibtexのほうがいいかも。
      * 自分はjbibtexはobsoleteだと思ってる。
  * 「LaTeX文書」よりも「pLaTeX文書」のほうがいいかも。
  * なぜ非掲載のdraftオプションを例で使っている？

**Comment by wtsnjp** [comment]
再びコメントありがとうございます．大変助かります．

後半はほとんどがケアレスミスです．自己校正が不十分なまま beta を出してしまい失礼致しました（引き続き誤植は確認していきます）．

簡単に修正できる問題は既に修正しました．以下は今後の修正に向けたメモやボヤキ，疑問に対する回答などです：

* 個人的に <長さを表す “命令”> などに違和感があるので “制御綴” という用語を導入したかったのですが（なので意図的でした）「LaTeX には “制御綴” という概念がない」のに冒頭「pLaTeX2e の基本」に掲載するのは確かによくないですね……
* 行分割・ページ分割周りの命令選択と説明の程度はなお思案中です（もちろん深入りは避けたい）
* 円記号（的ナニカ）を出力する方法は何かしら載せたいですが，妥当な方法が見つかっていません（寸法の直接指定は NG としたい）
* 数式クラス指定は有用なので（良い代替手段がなければ）妥協します
* 65536sp = 1in は私のミスですが『独習』p.67 にも同様の誤植があるのを発見しました
* `\printindex` は私も引っかかったことがあったのでそうでした．しかしこれは本当に弱りますね……特定パッケージ（仮に LaTeX 標準でも）に関わることは一切触れたくない（サンプルは除く）ですが，かといって索引をなかったことにしてしまうのも何だか
* 私も pbibtex がいいと思いますが “jbibtex しかない環境” は考慮しなくて大丈夫でしょうか
* draft オプションは単に消し忘れです

**Comment by zr-tex8r** [comment]
現状で「LaTeXは“標準”だけでは足りない」のは共通認識だと思います。その上で「“標準”だけに絞った資料」を作るのは有意義だとも思います。だけど、そういう前提である以上、その資料では「必要なのが足りないのは仕方がない」と割り切ることが必要な気がします。

  * （念のため） 円記号は textcomp を読み込んで `\textyen` です。私は（本来は）これを使うべきだと考えています。

長さを表す命令について。

  * LaTeXの公式の用語ではソレ（TeXの「寸法・グルーのレジスタ・パラメタ」に相当するもの）のことを“length command”といいます。例の“storage bin”と比べると「よく使われている用語」だと思います。
  * 自分は、昔は「長さ変数」というオレ用語を使っていたのですが、最近は公式に合わせて「長さ命令」を使っています。

「pbibtexかjbibtexか」について。

  * “pbibtex”が初めて登場したのは2009年。
  * だから「jbibtexしかないTeXシステム」は現在でも残っていえると思う。
  * だけど、それよりも「pbibtexしかないTeXシステム」の方が可能性が強い。例えば、TeX Liveでは（少なくともWindowsでは）“jbibtex”がかつて存在したことはない。

**Comment by zr-tex8r** [comment]
追加の「気になります」情報。

  * `\pragraph` じゃなくて `\paragraph`。
  * `\textless`・`\textgreater` は「括弧類」ではない気がする。
  * 「二項演算子」のところにある `\star` と `\circ` が「その他」のところにもある。
  * 2つある `\bigotimes` の片方は `\bigoplus` のはず。

**Comment by wtsnjp** [comment]
ありがとうございます．色々と修正作業中です．

追加のコメント等です：

* 「重ね打ち等で “記号を作る” 例として円記号を載せたい」という意図でした．ただ，やはり適当なパッケージを使うのが “正解” な気がしたのでやめておきます
* `\textless` 等は原版から引き継いだ問題ですね．わざとらしく「括弧 “類”」としたのはそのためですが，ミスリードな自覚はあるのでなるべく他にスペースを作って移します
* 「その他」にちょうど `\prime` と `\surd` が抜けていることに気付いたので差し替えます

**Comment by wtsnjp** [comment]
ご指摘いただいた点その他を修正し，v2.0-beta2 をリリースしました．
文書内のバージョン番号を変更し忘れましたが，ベータ版なのでいいことにします．

一時置き場：<https://wtsnjp.com/pdf/platexsheet-v2.0-beta2.pdf>

**Comment by wtsnjp** [comment]
v2.0 をリリースしました．CTAN への収録も申請済みです．
まだまだ改善の余地はあるだろうと思いますが，さしあたって「原版に存在する問題点の修正」は v2.0 リリースをもって完了したとみなし，本 issue は close します．
ご協力ありがとうございました．
