### ISSUE TITLE
[jsclasses] \narrowbaselines への言及

### ISSUE THREAD

**Issue by aminophen** [wtsnjp/platexcheat#3]
platexsheet-jsclasses において，\narrowbaselines について言及してもらえないでしょうか？

参考： https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2679

**Comment by wtsnjp** [comment]
言及するならこんな感じでしょうか？ ただ，この追加は微妙な気もしています：

* こんな簡潔な言及で利用者の役に立つか？（詳しく説明できるほど紙面の余裕はない）
* 行送りについてはそもそも例えば寸法命令 `\baselineskip` にも言及していないなか `\narrowbaselines` に言及するのは優先度的・難易度的に妥当か？（やはり紙面の都合で優先度の低いものに言及できないのは仕方がない）

**Comment by aminophen** [comment]
- こんな簡単な言及で利用者の役に立つか？
    - チートシートなので妥当かと。分からなければ詳しく調べるきっかけにはなりそうです。
- 優先度的・難易度的に妥当か？
    - \baselineskip などの組版パラメタはクラスファイル設計者が決定すべきで，ユーザが弄るべきではないと思います。\narrowbaselines はユーザ用命令なので，優先度的には妥当と思います。

とはいえ，追加するかどうかはお任せします。そもそも jsclasses にユーザ向けマニュアルがないのが問題なんですよね。（jsclasses.pdf はソースコード説明書であって，マニュアルではないと常々思っている）

**Comment by wtsnjp** [comment]
事実上の jsclasses のマニュアル相当である（と私が思っている）『美文書』の第7版でも p.149 に「参考」として小さい文字で載っている程度だったので，やはりそれほど優先度は高くないかなとという気がしていますが，今回はたまたま1行追加してもページ数が増えたりすることがなかったので，ひとまず追加しておくことにします．

ご提案ありがとうございました．
